CREATE TABLE products (
    product_code VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    description VARCHAR(1000),
    interest_rate NUMERIC(5, 4),
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE customers (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cif_number VARCHAR(20) UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    phone_number VARCHAR(20),
    address_line1 VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    country_code VARCHAR(2),
    kyc_status VARCHAR(20) DEFAULT 'PENDING',
    kyc_documents VARCHAR(4000) DEFAULT '{}',
    risk_rating VARCHAR(10) DEFAULT 'LOW',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE accounts (
    account_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    product_code VARCHAR(50) NOT NULL,
    account_number VARCHAR(20) UNIQUE NOT NULL,
    iban VARCHAR(34),
    balance NUMERIC(15, 2) DEFAULT 0.00,
    overdraft_limit NUMERIC(15, 2) DEFAULT 0.00,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    opened_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP,
    configurations VARCHAR(4000) DEFAULT '{}',
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (product_code) REFERENCES products(product_code)
);

CREATE TABLE transactions (
    transaction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL,
    reference_code VARCHAR(50),
    transaction_type VARCHAR(20) NOT NULL,
    amount NUMERIC(15, 2) NOT NULL,
    description VARCHAR(1000),
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    balance_after NUMERIC(15, 2),
    FOREIGN KEY (account_id) REFERENCES accounts(account_id)
);

-- Seed data
INSERT INTO products (product_code, name, category, interest_rate) VALUES 
('CHK-STD', 'Standard Checking', 'CHECKING', 0.00), 
('SAV-HYS', 'High Yield Savings', 'SAVINGS', 0.045);

INSERT INTO customers (customer_id, cif_number, first_name, last_name, date_of_birth, email, kyc_status) VALUES 
(1, 'CIF-100001', 'John', 'Smith', '1980-01-01', 'john.smith@example.com', 'COMPLETED'), 
(2, 'CIF-100002', 'Jane', 'Doe', '1982-02-02', 'jane.doe@example.com', 'COMPLETED'), 
(3, 'CIF-100003', 'Frodo', 'Baggins', '1984-03-03', 'frodo.baggins@example.com', 'COMPLETED');
ALTER TABLE customers ALTER COLUMN customer_id RESTART WITH 4;

INSERT INTO accounts (account_id, customer_id, product_code, account_number, balance, status) VALUES 
(1, 1, 'CHK-STD', '12345678', 1500.00, 'ACTIVE'), 
(2, 1, 'SAV-HYS', '87654321', 5000.00, 'ACTIVE'), 
(3, 1, 'CHK-STD', '11223344', 250.00, 'ACTIVE'), 
(4, 2, 'CHK-STD', '44332211', 3200.00, 'ACTIVE'), 
(5, 2, 'SAV-HYS', '55667788', 12000.00, 'ACTIVE'), 
(6, 3, 'CHK-STD', '99887766', 50.00, 'ACTIVE'), 
(7, 3, 'SAV-HYS', '66778899', 1000.00, 'ACTIVE'), 
(8, 3, 'CHK-STD', '10203040', 75.00, 'ACTIVE'), 
(9, 3, 'SAV-HYS', '40302010', 2500.00, 'ACTIVE');
ALTER TABLE accounts ALTER COLUMN account_id RESTART WITH 10;

INSERT INTO transactions (account_id, transaction_type, amount, description, balance_after) VALUES 
(1, 'DEPOSIT', 1000.00, 'Paycheck', 1000.00), 
(1, 'WITHDRAWAL', 50.00, 'ATM', 950.00);